#!/bin/sh

set -e -u

_err() {
  echo "$*"
  exit 1
}

repo_name="$1"
repo_name="${repo_name%/}"
repo_dir="${repo_name}"

if ! [ "${repo_name}" ]; then
  _err "you should provide repo_name of repository"
fi


if ! [ -d "${repo_dir}" ]; then
  _err "repo ${repo_dir}  doesn't exist"
fi

# we have repo, but it doesn't have export-ok file = invisible, don't delete
if [ -d "${repo_dir}" ] && [ -f "${repo_dir}/git-daemon-export-ok" ]; then
  _err "repo ${repo_dir} doesn't exist"
fi

echo "you're going to delete ${repo_dir} repo"
echo "type repository repo_name (\`${repo_name}\`) to confirm"
read -r confirm

if ! [ "$confirm" = "$repo_name" ]; then
  echo "invalid confirmation (${confirm} != ${repo_name})"
  exit 1
fi

rm -rf "${repo_dir}" || _err "failure removing ${repo_dir}!"
echo "${repo_dir} deleted successfully"
