#!/bin/sh

set -eu

_err() {
  echo "$*"
  exit 1
}

line_format="%-25s %-15s %-40s\n"
printf "$line_format" "NAME" "CATEGORY" "DESCRIPTION"

( 
	cd /var/www/repos || _err "git root doesn't exist!"
	
	for d in *; do
		if ! [ -f "$d"/config ]; then continue; fi
		name="${d%/}"
		category="$(git config get -f "${d}"/config gitweb.category 2>/dev/null)"
		description="$(git config get -f "${d}"/config gitweb.description 2>/dev/null)"

		printf "$line_format" "$name" "$category" "$description"
	done
)
