#!/bin/sh

set -eu

_err() {
  echo "$*"
  exit 1
}

table_line() {
	printf "%-25s %-15s %-40s\n" "$1" "$2" "$3"
}

table_line "NAME" "CATEGORY" "DESCRIPTION"

for d in ./*; do
	if ! [ -d "$d" ]; then continue; fi
	if ! [ -f "$d"/config ]; then continue; fi
	if ! [ -f "$d"/git-daemon-export-ok ]; then continue; fi

	name="${d%/}"
	category="$(git config get -f "${d}"/config gitweb.category 2>/dev/null)"
	description="$(git config get -f "${d}"/config gitweb.description 2>/dev/null)"

	table_line "$name" "$category" "$description"
done
