server "_default" {
    listen on $loopback port $httpd_plain_port
    listen on $loopback port $httpd_tls_port

    log {
        access "access.default.log"
        error "error.default.log"
    } 

    location * {
        block drop
    }
}