server "_default" {
    listen on $loopback port $redirect_port
    listen on $loopback port $serve_port

    log {
        access "access.default.log"
        error "error.default.log"
    } 

    location * {
        block drop
    }
}