server "pzskc383.dp.ua" {
    repos_path "/var/www/repos"
    site_name "pzskc383 project storage"
    site_owner "Alexander Dyadechko"
    logo_url "https://pzskc383.dp.ua/got/"
    max_commits_display 50
    custom_css "mono-gotweb.css"
    logo "serve.png"
    respect_exportok on
}
