# vi: set ts=4 sts=4 sw=4 et:
server:
    verbosity: 1

    interface: 127.0.0.1@53
    interface: ::1@53

    do-ip6: yes
    do-udp: yes
    do-tcp: yes

    access-control: 0.0.0.0/0 refuse
    access-control: 127.0.0.0/8 allow
    access-control: ::0/0 refuse
    access-control: ::1 allow

    hide-identity: yes
    hide-version: yes

    qname-minimisation: no

    auto-trust-anchor-file: "/var/unbound/db/root.key"
    aggressive-nsec: yes

    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: yes

    module-config: "validator iterator"
    tcp-upstream: yes
    do-not-query-localhost: no

    cache-min-ttl: 300
    # serve-expired: yes

    # interface: 127.0.0.1@853
    # interface: ::1@853
    # tls-port: 843
    # tls-service-key: "/etc/ssl/private/fqdn.key"
    # tls-service-pem: "/etc/ssl/fqdn.crt"

remote-control:
    control-enable: yes
    control-use-cert: no
    control-interface: /var/run/unbound.sock

# RFC 8806
# also: https://www.internic.net/domain/root.zone
auth-zone:
    name: "."
    master: "b.root-servers.net"
    master: "c.root-servers.net"
    master: "d.root-servers.net"
    master: "f.root-servers.net"
    master: "g.root-servers.net"
    master: "k.root-servers.net"
        fallback-enabled: yes
    for-downstream: no
    for-upstream: yes
    zonefile: "/var/unbound/db/root.zone"


